
camunda.bpm.admin-user:
  id: admin
  password: camadmin

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/banking_app
    username: root
    password: admin
    driver: com.mysql.jdbc.Driver